### PR TITLE
Additional device trees with vfd support

### PR DESCRIPTION
**Pull request by spycat88**
PR to add DTS for Sunvell T95M to add support for VFD, sent to me by @arthur-liberman

### CODE REVIEW

**Comment by spycat88** [comment]
I'm not sure this is ready for merging yet, closing PR now

**Comment by kszaq** [comment]
Was this PR closed because it needs amendments or is something wrong with it?

**Comment by spycat88** [comment]
I need to check with the author of the new driver something as he has started adding more options to support even more devices but hasn't pushed the code yet, in which case if he is planning on adding more options that need to be specified then there is no point in merging yet as more additions will be required.

**Comment by spycat88** [comment]
Re-opened

Added the other DTB's I have been sent to this PR as well, they have all been tested by forum users.

**Pull request merged**
